# Generated by Django 5.2.7 on 2025-10-18 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='matched_list',
        ),
        migrations.RemoveField(
            model_name='inventoryaudit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealplanentry',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealingredient',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealingredient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealplanentry',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='generated_from',
        ),
        migrations.RemoveField(
            model_name='pantrylocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='Untitled Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_items', models.ManyToManyField(related_name='inventory_lists', to='api.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PantryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='pantry_requirements', to='api.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerPlan',
        ),
        migrations.DeleteModel(
            name='InventoryAudit',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealIngredient',
        ),
        migrations.DeleteModel(
            name='MealPlanEntry',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
        migrations.DeleteModel(
            name='PantryLocation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
