# Generated by Django 5.2.7 on 2025-10-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inventoryaudit_matched_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylist',
            name='user',
        ),
        migrations.DeleteModel(
            name='PantryRequirement',
        ),
    ]
