# Generated by Django 5.2.7 on 2025-10-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shoppinglist_remove_inventoryitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
